DROP DATABASE IF EXISTS Juego;
CREATE DATABASE Juego;

USE Juego;

CREATE TABLE JUGADOR (
    JUGADORID INT NOT NULL,
    NOMBRE VARCHAR(20),
    PASSWORD VARCHAR(20),
    PRIMARY KEY (JUGADORID)
)ENGINE=InnoDB;

CREATE TABLE PARTIDA (
    PARTIDAID INT NOT NULL,
    FECHAPARTIDA DATE NOT NULL,
    DURACIONPARTIDA INT NOT NULL,
    GANADORPARTIDA INT,        
    PRIMARY KEY (PARTIDAID),
    FOREIGN KEY (GANADORPARTIDA) REFERENCES JUGADOR(JUGADORID)
)ENGINE=InnoDB;

CREATE TABLE COMPETICION (
    JUGADOR_ID INT NOT NULL,
    PARTIDA_ID INT NOT NULL,
    FOREIGN KEY (JUGADOR_ID) REFERENCES JUGADOR(JUGADORID),
    FOREIGN KEY (PARTIDA_ID) REFERENCES PARTIDA(PARTIDAID),
    PRIMARY KEY (JUGADOR_ID, PARTIDA_ID)
)ENGINE = InnoDB;

INSERT INTO JUGADOR (JUGADORID, NOMBRE, PASSWORD)
VALUES (1, 'yassir', 'upc');
INSERT INTO PARTIDA (PARTIDAID, FECHAPARTIDA, DURACIONPARTIDA, GANADORPARTIDA)
VALUES (1, '2023-10-01', 25, 1);
INSERT INTO COMPETICION (JUGADOR_ID, PARTIDA_ID)
VALUES (1, 1);

